nota1=int(input("Ingrese la primera nota: ")) #INPUT Recibir un dato (ENTRADA)
nota2=int(input("Ingrese la segunda nota: ")) #INT convertir el dato en entero (numero)
nota3=int(input("Ingrese la tercera nota: "))
promedio=(nota1+nota2+nota3)/3 #Operacion requerida (PROCESO)
print(promedio) #PRINT es para mostrar la informacion requerida (SALIDA)